#!/bin/sh
set -ex
REPOROOT=$(cd $(dirname $0)/../../../ && pwd -P)
cd $REPOROOT
env|grep -v COVERALLS_REPO_TOKEN
if [ "$BUILD_TYPE" = "coverage" ]; then
    # cpp-coveralls v0.4.0 fails with the container I am using
    # to build; see https://github.com/eddyxu/cpp-coveralls/issues/130
    https://github.com/eddyxu/cpp-coveralls@master
fi
if [ -x autogen.sh ]; then
    ./autogen.sh --cmake --context=ci
fi
tc qdisc add dev eth0 root netem delay 200ms 10ms # Reduce speed
cmake $CMAKE_OPTIONS .
cmake --build . -- $CMAKE_BUILD_OPTIONS
ctest $CTEST_OPTIONS
if [ "$BUILD_TYPE" = "coverage" ]; then
    $HOME/.local/bin/coveralls --gcov-options '\-lp' --build-root .            \
          $COVERALLS_OPTIONS
fi
