#!/bin/sh
set -ex
REPOROOT=$(cd $(dirname $0)/../../../ && pwd -P)
cd $REPOROOT
env|grep -v COVERALLS_REPO_TOKEN|grep -v CODECOV_TOKEN
if [ "$BUILD_TYPE" = "coverage" ]; then
    pip install --user cpp-coveralls
fi
if [ -x autogen.sh ]; then
    ./autogen.sh --cmake --context=ci
fi
tc qdisc add dev eth0 root netem delay 200ms 10ms # Reduce speed
cmake $CMAKE_OPTIONS .
cmake --build . -- $CMAKE_BUILD_OPTIONS
ctest $CTEST_OPTIONS
if [ "$BUILD_TYPE" = "coverage" ]; then
    if [ "$CODECOV_TOKEN" != "" ]; then
        curl -fsSL https://codecov.io/bash | bash
    fi
    $HOME/.local/bin/coveralls --gcov-options '\-lp' --build-root .            \
          $COVERALLS_OPTIONS
fi
