#!/bin/sh
set -e
REPOROOT=$(cd $(dirname $0)/../../../ && pwd -P)

if [ $# -ne 2 ]; then
    echo "usage: $0 docker-image-name script-name" 1>&2
    exit 1
fi

docker_image=$1
script_name=$2

# Travis overrides the CC and CXX set by us. Re-instate them.
if [ "$TRAVIS_BRANCH" != "" -a "$MK_CC" != "" ]; then
    CC=$MK_CC
fi
if [ "$TRAVIS_BRANCH" != "" -a "$MK_CXX" != "" ]; then
    CXX=$MK_CXX
fi

docker run                                                                     \
    --cap-add=NET_ADMIN                                                        \
    -e "BUILD_TYPE=$BUILD_TYPE"                                                \
    -e "CC=$CC"                                                                \
    -e "CMAKE_BUILD_OPTIONS=$CMAKE_BUILD_OPTIONS"                              \
    -e "CMAKE_OPTIONS=$CMAKE_OPTIONS"                                          \
    -e "COVERALLS_OPTIONS=$COVERALLS_OPTIONS"                                  \
    -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN"                            \
    -e "CODECOV_TOKEN=$CODECOV_TOKEN"                                          \
    -e "CFLAGS=$CFLAGS"                                                        \
    -e "CPPFLAGS=$CPPFLAGS"                                                    \
    -e "CTEST_OPTIONS=$CTEST_OPTIONS"                                          \
    -e "CXX=$CXX"                                                              \
    -e "CXXFLAGS=$CXXFLAGS"                                                    \
    -e "LDFLAGS=$LDFLAGS"                                                      \
    -e "MAKEFLAGS=$MAKEFLAGS"                                                  \
    -e "TRAVIS_BRANCH=$TRAVIS_BRANCH"                                          \
    -e "VERBOSE=$VERBOSE"                                                      \
    -e "V=$V"                                                                  \
    -v $REPOROOT:/mk                                                           \
    $DOCKER_OPTIONS                                                            \
    $docker_image                                                              \
    /mk/.ci/docker/script/$script_name
