#!/bin/sh
set -e
REPOROOT=$(cd $(dirname $0)/../../../ && pwd -P)

if [ $# -ne 2 ]; then
    echo "usage: $0 docker-image-name script-name" 1>&2
    exit 1
fi

docker_image=$1
script_name=$2

docker run                                                                     \
    --cap-add=NET_ADMIN                                                        \
    -e "CC=$CC"                                                                \
    -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN"                            \
    -e "CFLAGS=$CFLAGS"                                                        \
    -e "CPPFLAGS=$CPPFLAGS"                                                    \
    -e "CXX=$CXX"                                                              \
    -e "CXXFLAGS=$CXXFLAGS"                                                    \
    -e "LDFLAGS=$LDFLAGS"                                                      \
    -e "TRAVIS_BRANCH=$TRAVIS_BRANCH"                                          \
    -v $REPOROOT:/mk                                                           \
    $docker_image                                                              \
    /mk/.ci/docker/script/$script_name
